### ISSUE TITLE
Create a Vue package for Davatar

### ISSUE THREAD

**Issue by carlosdp** [metaphor-xyz/davatar-helpers#7]
## Description
We currently have a `@davatar/react` package that adds ENS avatar support to any React web3 project. Now, we should add a new `@davatar/vue` package that exposes Vue components for Vue projects, of which there are many in web3.

## Tasks
- [ ] Refactor the metadata fetching logic in the `@davatar/react` [<Image />](https://github.com/TBDAO/davatar-helpers/blob/master/packages/react/src/Image.tsx) component into a new `@davatar/core` package that will be shared among the other packages.
- [ ] Create a new `@davatar/vue` package that exposes a core `<davatar />` component (which shows an avatar based on the ENS name), and an `<image />` component (which fetches the metadata for a known ENS avatar URI). Names can be changed if they need to in order to match convention.
- [ ] Create an `example` project in that vue package, just like the react one, that shows the working functionality. Or, alternatively, write proper tests.

## Resources
- [ENS Avatar Spec](https://gist.github.com/Arachnid/9db60bd75277969ee1689c8742b75182)
- [@davatar/react package](https://github.com/TBDAO/davatar-helpers/tree/master/packages/react)
